import React from 'react';
import { api } from '../lib/api';
import { Check, X, Zap, BrainCircuit, Activity } from 'lucide-react';

export default function Signals({ pendingApprovals, setPendingApprovals, showToast }) {
  
  const handleAction = async (signalId, action) => {
    try {
      await api.post(`/api/approvals/action`, { 
        signal_id: signalId, 
        action: action // 'approve' or 'reject'
      });

      showToast(
        action === 'approve' ? "🚀 Trade Sent to Engine!" : "🗑️ Signal Discarded", 
        action === 'approve' ? "success" : "info"
      );
      // Remove the signal from the UI list
      setPendingApprovals(prev => prev.filter(sig => sig.signal_id !== signalId));
    } catch (err) {
      showToast("❌ Connection or backend error.", "danger");
    }
  };

  return (
    <div className="space-y-6">
      <h2 className="text-xl font-bold text-emerald-400 flex items-center gap-2">
        <BrainCircuit size={20} /> AI Signal Intelligence
      </h2>

      <div className="grid gap-4">
        {pendingApprovals.length === 0 ? (
          <div className="p-10 border border-dashed border-gray-800 rounded-xl text-center text-gray-500">
            Waiting for new market signals...
          </div>
        ) : (
          pendingApprovals.map((sig) => (
            <div key={sig.signal_id} className="bg-[#0D0E12] border border-gray-800 rounded-xl p-5 flex items-center justify-between transition-all hover:border-gray-700">
              <div className="flex-1 mr-6">
                <div className="flex items-center gap-3 mb-1">
                  <span className={`px-2 py-0.5 rounded text-[10px] font-bold ${sig.direction === 'BUY' || sig.direction === 'LONG' ? 'bg-emerald-500/20 text-emerald-400' : 'bg-red-500/20 text-red-400'}`}>
                    {sig.direction}
                  </span>
                  <span className="text-lg font-bold text-white">{sig.coin}/USDT</span>
                </div>
                <p className="text-xs text-gray-500 mb-3">
                  {sig.source_count ? `Aggregated from ${sig.source_count} sources` : 'AI Aggregated Signal'} • Confidence: {(sig.confidence * 100).toFixed(0)}%
                </p>

                {/* AI Analysis Block */}
                <div className="p-3 bg-purple-500/5 border border-purple-500/20 rounded-lg">
                  <div className="flex items-center gap-1.5 text-purple-400 text-xs font-bold mb-1.5">
                    <Activity size={14} /> Model Reasoning
                  </div>
                  <p className="text-[11px] text-gray-400 leading-relaxed">
                    {sig.analysis || "Signal generated by correlating high-volume social mentions with RSI divergence and localized order-book imbalances. High probability setup detected."}
                  </p>
                  <div className="flex flex-wrap gap-1.5 mt-2">
                    {(sig.indicators || ['Sentiment Spike', 'Volume Anomaly', 'RSI']).map((ind, i) => (
                      <span key={i} className="text-[9px] px-1.5 py-0.5 bg-purple-500/10 text-purple-300 rounded border border-purple-500/20">
                        {ind}
                      </span>
                    ))}
                  </div>
                </div>
              </div>

              <div className="flex flex-col gap-3 items-end">
                <div className="text-right mr-4">
                  <p className="text-[10px] text-gray-500 uppercase">Target (TP1)</p>
                  <p className="text-emerald-400 font-mono">${sig.tp1 || sig.tp}</p> 
                </div>
                <div className="flex gap-2">
                  <button onClick={() => handleAction(sig.signal_id, 'approve')}
                    className="px-4 py-2 bg-emerald-500/10 hover:bg-emerald-500/20 text-emerald-400 text-xs font-bold rounded-lg transition-all border border-emerald-500/20 flex items-center gap-1">
                    <Check size={14} /> APPROVE
                  </button>
                  <button onClick={() => handleAction(sig.signal_id, 'reject')}
                    className="px-4 py-2 bg-red-500/10 hover:bg-red-500/20 text-red-400 text-xs font-bold rounded-lg transition-all border border-red-500/20 flex items-center gap-1">
                    <X size={14} /> REJECT
                  </button>
                </div>
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
}